version: '2'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432

  assistant-app:
    container_name: assistant_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - assistant-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 