version: '2.1'
services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres:13.0-alpine
    privileged: true
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - db_network

  assistant_app:
    container_name: assistant_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres_db

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - postgres_db

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data: